all:
  hosts:
    node1:
      ansible_host: 89.169.132.91
      ip: 10.10.1.31
    node2:
      ansible_host: 158.160.5.148
      ip: 10.10.2.5
    node3:
      ansible_host: 158.160.159.48
      ip: 10.10.3.32
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
